### PR TITLE
Fixing a compatibility issue from IDA 7.0 -> 7.1 where the 'sizes' at…

### PR DESCRIPTION
**Pull request by soggysec**
Fixing a crash in IDA 7.1 where the "sizes" attribute is no longer exposed in python.

### CODE REVIEW

**Comment by soggysec** [comment]
As mentioned in the commit descriptions, this fixes two instances of IDA 7.0 -> IDA 7.1 compatibility (while maintaining backwards compatibility). It also fixes a missed encode/decode issue where Segment changes would cause a crash

**Comment by NeatMonster** [comment]
Thank you for the pull request @soggysec, it's very much appreciated!

**Comment by soggysec** [comment]
Sure thing! great work. A buddy and I have actually forked this in another repo to add idaenv support. Take a look: 

https://github.com/deactivated/idaenv -- IDAPython Plugin Management
https://github.com/deactivated/idaenv-plugins -- IDA Python Plugins that have been ported to use IDAENV

**Comment by NeatMonster** [comment]
> A buddy and I have actually forked this in another repo to add idaenv support.

That's interesting, though I don't want to force any extra dependencies on our users. It looks like it, but would it be possible to have *optional* support for `idaenv`? Do you need to source the IDA Pro virtual environment to start the server?

**Comment by deactivated** [comment]
It's definitely possible to include optional support for idaenv. All that idaenv really requires is a `setup.py` file with an `idapython_plugins` entry point. Copy-paste workflows should be unaffected. And although I think idaenv is best used with dedicated virtual environments, it supports `pip install --user ...` and `sudo pip install ...` just as well.

The `setup.py` file in my repo also uses the `console_scripts` entry point for the server; I personally find that configuration convenient, but it's essentially unrelated to idaenv.

**Comment by NeatMonster** [comment]
Thank you for the detailed answer @deactivated. If you can write a pull request enabling `idaenv` without interfering w/ the other installation methods (copy-and-paste and easy_install), then I'm all for it!

**Pull request merged**
